//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Twix_Rezerwacja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Twix_Rezerwacja()
        {
            this.Twix_Bron_Amunicja = new HashSet<Twix_Bron_Amunicja>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_KLIENTA { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<int> CZAS { get; set; }
        public Nullable<int> ID_TORU { get; set; }
    
        public virtual Twix_Klienci Twix_Klienci { get; set; }
        public virtual Twix_SL_Torow Twix_SL_Torow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Twix_Bron_Amunicja> Twix_Bron_Amunicja { get; set; }
    }
}
